### ISSUE TITLE
Is this normal ? : vendored packages not getting saved in a bitbucket repo

### ISSUE THREAD

**Issue by gedw99** [Masterminds/glide#106]
Not sure if this is correct thing it should do, but basically locally i have a few github packages in my Vendor directory.

Steps:
```
glide get github.com/wayn3h0/go-uuid
Oops! Package 'github.com/wayn3h0/go-uuid' is already in glide.yaml

git add .
git commit -am "added UUID package"
git push

```
But after pushing to my bitbucket account i don't see the vendored files, but instead a reference like this.
Clicking on the reference does nothing.
 See image attachent.

<img width="1280" alt="screen shot 2015-10-14 at 16 00 25" src="https://cloud.githubusercontent.com/assets/155690/10485894/bf51cea8-728c-11e5-81fa-c9905092e802.png">

**Comment by mattfarina** [comment]
@gedw99 This is a git thing. Let me explain.

When git sees another git repo it treats it as a submodule which is what you have here. This is not how we recommend you do things. Submodules can be powerful but can add an extra complication.

What we usually suggest is that you add `vendor/` to your gitignore. Then the packages aren't checked into your local project but are instead ignored all together. If someone wants to get the packages they can run `glide install` and get them. They can even get the versions you specified in your `glide.yaml` file.

if you want to stored the packages in your projects vcs, also known as vendoring, you can remove the `.git` directory form each project in the `vendor/` folder. When you add, commit, and push the files they will show up in your project. When you run `glide up` it will see that you vendored the packages and check for updates. It will need to clone the repos to compare for updates so updating becomes a more expensive operation.

Hope this helps.

**Comment by gedw99** [comment]
I want to vendor them, so u can get the exact code back in case the github repo disappears.
Hence why I did not add a .gitignore.

In your last paragraph you explain how to do this. But I don't see how its different from what I am doing anyway.
Could you try again

**Comment by mattfarina** [comment]
@gedw99 you left the `.git` directory in each vendored project. That causes git to see those as submodules which caused what you saw. If you don't want that just delete the .git directory from each project you pulled down into the `vendor/` folder. Commit those projects to your codebase rather than using submodules. Then you can keep using Glide to manage updates as it will see that you vendored the code and handle it.

**Comment by gedw99** [comment]
OK makes sense. Will do it. Thanks

**Comment by b-hayes** [comment]
Found this pretty annoying because bitbucket implicitly makes this happen on the remote when it has not happened on the local copy. Was really confusing as we could see a sub-module was created but locally there was no trace of a sub-module that we could fix.

Creates a huge problem for hours as the our server was crashing because a required file was missing after a pull.
