### ISSUE TITLE
More convenient install options?

### ISSUE THREAD

**Issue by dnephin** [Masterminds/glide#110]
Hello,

I'm looking at installing `glide` in a docker container. The current options are: source (requires git and make, and is a much larger download), or binary package (requires `unzip`).  

For a quick install, the binary package would normally be a great option, the problem is that it's not just a binary, it's in a zip archive! `unzip` doesn't even support un-compressing from stdin, so now I also need to create a temporary file.

Any way you'd consider either a plain binary download (no zip archive, just the binary), or using `.tar.gz` instead of zip?

**Comment by technosophos** [comment]
FWIW, I toyed around with a few Dockerfiles. Here they are so you can take a look: https://github.com/technosophos/goglide I doubt that they'll meet your current requirements, but if you have any improvements, I'd love to hear. I was playing with the ONBUILD directives so that an ideal Dockerfile might look like 

```
FROM onglide
COPY . /app
```

(Or something like that.)

Okay... to you're actual point...

I am for the idea of distributing as a tgz file instead. We just need to modify this build target, I think: https://github.com/Masterminds/glide/blob/master/Makefile#L35

What's your opinion, @mattfarina?

**Comment by mattfarina** [comment]
@dnephin what would your ideal set of options be? Docker image? Straight binary? I'm happy to try and comply with more options.

**Comment by dnephin** [comment]
Single file binary install would be my preferred option. It makes it easy to install into an image with `curl`+`chmod`.

`.tar.gz` would be my second choice, since I can extract just a single file to stdout (not supported by zip).

**Comment by mattfarina** [comment]
Thanks. When I do the 0.7.0 release I'll rework the options.
