### ISSUE TITLE
Glide gets dependencies in vendor and in $GOPATH/src at the same time

### ISSUE THREAD

**Issue by leonfs** [Masterminds/glide#127]
Hi,

I've been experiencing a problem in which glide installs my dependencies not only on the vendor folder but also at the src path. Basically duplicating every dependency.

I'm running the latest build of Glide: glide version 0.6.1-70-g84dba35

**Comment by mattfarina** [comment]
@leonfs thanks for the feedback. We're trying some new "caching" strategies. We'd like glide to be smarter. when would you like this smarts to work? Any thoughts?

Right now it tries to put or use a copy in the gopath. If it can't it tries in a cache folder.

I'm very open to thoughts on this. We can use flags to provide changes.

What do you think and why?

**Comment by mattfarina** [comment]
@leonfs I've been unsure of the aggressive caching being on by default. That included pulling things to the `$GOPATH` by default. I've updated the aggressive nature to be opt-in. In the 0.8.0 release we'll look at improving this. See #128 as an option.

What do you think?

**Comment by gedw99** [comment]
Its confusing how it works now.

If it always uses the Vendor path then its clear.
Even if i have to try to build stuff in vendor to find it has dependencies that i need to add to the glide file, at least its clear, and the glide guess command helps.

this is essentially forcing glide to always put packages that depend on other packages as a flat structure in the vendor folder, rather then a tree.

It might be best to allow tree versus flat to be decided in the glide config too ? I am bringing this up because its hard to get this right automatically for everyone.

**Comment by mattfarina** [comment]
@gedw99 unfortunately, doing it as a tree breaks things. I posted an example at http://github.com/mattfarina/golang-broken-vendor. We tried a tree first and ran into practical issues.

**Comment by mattfarina** [comment]
Just prior to the release of `0.7.0` I fixed this issue. If there is still a problem with the original issue please let me know.
