### ISSUE TITLE
Scan imports for other imports to manage

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#146]
Right now Glide imports the files listed in the `glide.yaml` file and imports that are managed by Godep, GPM, and gb. There is a request and attempt to pull in and manage other packages. For example, we could detect an import of a dependencies dependency and even pin to a version for that.

There's a branch `feat/code-scanning` for this work.

Other issues have referenced the work on this over time including #145 and #125.

**Comment by mattfarina** [comment]
Note, the code in ae478dcfd64a5cfe1892a6aab1d6639261484b1e happens to scan core packages (GOROOT) such as `io`. I've seen this be slow for some reason.

**Comment by technosophos** [comment]
Here's the diagram for how we could do this:
![glide-init-state](https://cloud.githubusercontent.com/assets/89193/11357904/f6de31d8-9229-11e5-95ca-716092d4a1fc.png)

The source for the diagram (generated with PlantUML) is here:
https://gist.github.com/technosophos/7c5139be3a068145a262

**Comment by mattfarina** [comment]
@technosophos I'm trying to figure out where the separation between `glide init` and `glide up` happens and what goes in the `glide.yaml` file. Will a `glide init` create an initial `glide.yaml` file and perform all the actions of a `glide up`? Are you planning that the `glide.yaml` only has the deps from the `List Deps` step near the start while the `glide.lock` contains everything?

I ask for scanning because this has to do with how much scanning happens at what steps. Does the `glide init` scanning need to scan the dependencies? Or, does that wait until `glide up`?

I have my ideas but I wanted to get yours.

**Comment by dopgm** [comment]
@mattfarina 

2c. 
Was just thinking about handling subdependencies and realized that we have an issue: 
- suppose we lock version numbers of the declared packages
- in other dep. managers (bower, composer) all packages have declaration files of their own, thus if you lock the "top" package, you 1) can keep the subdependencies 2) do not need to specifically discover them, just read the declaration file (a-la glide.yml) in the root of each package
- EXCEPT for the cases when subdeps will use *, or ^ for compat
- so majority if not all existing managers are suffering from this - even locking top packages explicitly theres no guarantee that the new update won't break the code

SO
Two things:
1. If we want to implement at least standard locking, we need to require ALL packages to have their own dep management. ta-da
2. It took me quite a while to go from "composer install" during releases to... pushing ALL dependency/vendor folder into the repo (same for bower). Just don't laugh... That turned out to be the safest method to sleep well and proved itself multiple and multiple times. I remember cursing several times at Amazon during 2015 for changing auth schemes (invisibly for me) in their SDK package on some my projects w/o full vendor/deps in git. If you'll google this topic, you'll find quite a number of arguments pro and con, with pro arguments primarily coming from more mature devs.

OK, #2 was a little leading to a different topic, but in fact my proposal would be create a dependency management standard requiring all packages to have a declaration file. Yes, this may be similar to same code existing for bower and npm, but so what? If Glide is more comfortable this idea will get traction as the dep management is beneficial for package developers as well.

Sorry for maybe somewhat chaotic thoughts, just in between other tasks in a hurry, but hope you got the idea. W/o support from package developers you'll have to do their work youreself - scan, guess their deps, make decision on wether to lock subdep versions or allow them be upgradeable etc.

Best!
D.

**Comment by mattfarina** [comment]
@dopgm so, here's the thought right now and I'll relate it to npm/composor.

We create a `glide.lock` file. This is similar to `npm shrinkwrap` or `composer.lock`. If there's a `composer.lock` it contains the pinned versions (e.g., commit id or tag which is an alias to a commit id). `composer install` looks for a `composer.lock` file and if present uses those pinned versions.

Then `glide install` looks for the `glide.lock` file and installs the pinned versions. `glide update` can be used to update the `glide.lock` file based on the versions or ranges specified in the `glide.yaml` file.

For projects that don't manage their own dependencies we get those and lock to a commit id. This way you install the locked version and it's always reproducible.

Others, like Rust (Cargo) and PHP (Composer), do this today. It also solves for packages that don't do anything special to specify their versions. We can still pin them.

**Comment by dopgm** [comment]
@mattfarina 
Yes, sounds really good.

> For projects that don't manage their own dependencies we get those and lock to a commit id. This way you install the locked version and it's always reproducible.

Yep. Just to make sure we are on the same page: we are still looking for glide.lock in all dependencies. If found - using it. If not found - doing our own scan. Sounds right?

Btw.
@mattfarina @technosophos 
Here's a really good article on install/update/lock : https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file

**Comment by mattfarina** [comment]
Scanning unmanaged imports (and the lockfile) are on master now. Closing. If there's something else please let us know.
