### ISSUE TITLE
Feature Request: `glide prune` - remove unused files from vendor/

### ISSUE THREAD

**Issue by dnephin** [Masterminds/glide#176]
I've been using glide for personal projects, but when I've tried to suggest it to a couple of other developers for larger projects, both times I've received the same complaint. `glide` leaves all the files from the dependency repo in place.

I understand this makes sense for the workflow `glide` suggests (which is to put `vendor/` in `.gitignore`, not check it in), but not everyone is sold on this idea. 

I think what they're looking for is a way to remove the unused files so they can check in just the important `.go` files (and of course licenses) without including a bunch of unnecessary files.

The easiest files to remove would be:
* any unused package that isn't listed in `subpackage`
* any flattened packages in `vendor/` or `Godeps/` (not sure if this is done already?)
* any test files (`*_test.go`)

A more aggressive solution could use the import graph and remove any subpackage that isn't imported.

This command would be an option step after doing up, when changing a dependency.

Do you think something like this would be considered?

**Comment by LK4D4** [comment]
Also, up could be much faster if glide wouldn't download all subdepndencies.
For example, I use `github.com/docker/docker/pkg/pubsub`, glide downloads the whole docker, and it's dependencies(like libnetwork, grpc).
Import graph definitely should be used.

**Comment by mattfarina** [comment]
These two things have already come up.

The prune functionality in #143. Pruning was part of the plan from the beginning of locking and `glide up` has a `--delete` flag today. There has been discussion, and I'm sorry I don't remember the issue, as to the the level of pruning. How aggressive should it be and why?

In #166 we've been discussing having a smarter way to scan the codebase and pull down dependencies.

Using the import graph can be problematic. For example, when actively developing if you specify packages that have dependencies that have not been pulled down. Or another example, if you try to prune out parts of Docker other than the sub-package you're going to spend more time and work on updates.

It's worth noting, you shouldn't delete all licenses. To do so will violate many licenses. Many companies need to make sure take care of this so a tool that does that by default will be difficult for them.

I'm basically saying, it's complicated so we're being careful to think this through.

Both of these are really the result of monorepos in projects like docker and kubernetes. It's one of the dangers of monorepos. Unfortunately, I've heard a lot of complaining about this problem in docker and k8s. To ease the burden in other platforms in other languages I've seen many systems be logically broken up which eases that pain.

[If you're looking for a Docker API library I'd recommend looking at their recommendation list](https://docs.docker.com/engine/reference/api/remote_api_client_libraries/).

We're not going to build Glide for every use case for everyone. You can't make all the people happy all the time. I'm saying that when it comes to this stuff we will put thoughtful consideration into it. Still working out what that means and what a wise opinion here would mean.

**Comment by technosophos** [comment]
It seems impossible to please everyone on this, and I don't think we will be able to. But we're working our way toward what we think will be the happy medium.

### Follow the Leaders

Rather than make arbitrary decisions, we're trying to learn as much as we can from other package managers. I have yet to see one that computationally removes files from dependencies. So I'm not strongly inclined to do that simply because a few developers want it. If you could point to existing package managers that implement patterns like the things you are asking for, I'd like the chance to learn from them.

When it comes to removing files from external projects, I would really like to understand why this is a desired feature. Is it because disk space on a dev workstation is not available? Is it because some CI/CD system doesn't like it? When we're talking about just a few k (if that) of files, what's the impetus to incur the computational overhead it would take to remove and then continually manage those files.

### Don't Modify Package Contents

There's widespread _dis_agreement on which files should be removed. Removing `vendor` will actually break some packages (etcd immediately comes to mind). A few developers have informed me that it is a requirement of theirs that they be able to run `go test` on all of their dependencies. And there are licenses, like LGPL, that have serious legal ramifications if we modify the package computationally.

### Faster

Performance is a frequently cited issue. Many people seem to have some internal target for how long they think an update should take. We're trying to speed things up, but we've opted for correctness first (which, of course, is the right order). Even with huge repos like Kubernetes, I don't typically see updates that last for more than a few minutes. And since update should be an infrequent operation, this doesn't seem like a terrible thing to me. But I think we can cut it by 50% by implementing @mattfarina's parallelized git fetches.

### How many dependencies do we fetch?

It's sometimes hard to know, based on the code currently in a repo, which pieces of the code are going to be used in the future. It's not a particularly good developer experience to partially pull dependencies based on a code scan at time t, only to have builds fail at time t+1 because the developer imported a package from a project that they already fetched, but that was missing dependencies that we did not resolve. To take @LK4D4's case, the issue there is intent. Glide can't tell whether LK4D4 _intends_ to only use that subpackage, or if that's just the first subpackage the code happens to be importing when the dev runs `glide up`. Maybe @LK4D4 is only planning on using `pkg/pubsub`, or maybe that's just the first piece, and a moment later LK4D4 is going to also add `api/types`. I, for one, think it's sort of strange that we would download the entire source code for a package, but only allow for some percentage of it to build correctly. _But_, I understand why some people want it, especially when working with giant monorepos like Docker and Kubernetes.

In the near term, we've opted to simply prevent that problem by fetching all of the dependencies during a `glide up`. But we're looking at optimizing that process (mainly by guessing intent based on the import graph). Maybe we will just get really aggressive about only traversing narrow paths, and just pass the onus on to the developer to have to run `glide up` every time they add a new `import` to their code. It feels like a stilted workflow, but it would definitely trim down the number of dependencies.

So that's under active consideration. (I actually had code to do it, but abandoned it because I found it annoying to have to keep re-scanning things I already downloaded.)

### Checking in dependencies

Finally, there's the issue of checking in dependencies. I know that the Go community does this sometimes. I guess we'll support it in Glide. But it's a painful workflow to deal with. Every update has to completely re-pull the entire upstream source code repository for every touched dependency, which is like incurring the initial `glide up` overhead on every single update. Modifications to the local source tree become untraceable to Glide, and we have to start worrying about things like accidentally overwriting someone's local modifications. In short, it's an exercise in trying to guess whether the remote state is more important than the local state, but without all of the usual tools that help (e.g. git, mercurial, and bzr).

When the `vendor` directory contains VCSes, then Glide can track state in a meaningful way. So we strongly prefer that. Yes, it means that the initial checkout takes longer. But the trade-off is a long-term more reliable way of managing the dependencies.

If you take a look at the checked-in dependencies in Kubernetes, you'll see how badly that system eventually degenerates. There are a number of dependencies in that tree that are aging poorly. (Some of the packages there have moved to different domains or GitHub projects, even.) But the longer these packages stay checked in as-is, the harder it gets to keep them updated. Security issues sneak in. Bugs go unfixed. When we actively track this stuff in Glide, we can help the developer avoid this.

All we're really trying to do is build a really strong tool. While Go has some differences from other languages, it's not _so_ different that we need to re-invent dependency management. While we know that we can't please all developers all of the time, we're just trying really hard to build a tool that implements the best practices. It'll still take us some time, though, to sort out exactly how to do that.

**Comment by LK4D4** [comment]
@technosophos godep is an example of package manager that does that. However, I agree that you shouldn't try to satisfy everyone with Glide.

**Comment by technosophos** [comment]
We were basically convinced by this issue and a few others that we should change our approach on dependency resolution. In Glide 0.9, we now _only_ fetch packages that are required to build. (Basically, we switched from tree scanning to import scanning).

Thanks for convincing us.

Does that solve this issue, @LK4D4 and @dnephin?

**Comment by dnephin** [comment]
Sounds like it, thanks!

**Comment by LK4D4** [comment]
@technosophos Thanks!
