### ISSUE TITLE
Details on How Cache Works

### ISSUE THREAD

**Issue by jeffellin** [Masterminds/glide#178]
Wondering how cache works.  The docs mention

    Repository caching including reuse of packages in the $GOPATH

Does this mean that if the library exists in GOPATH it will not be downloaded again?   If yes how does the cache match to the version found in the lockfile?

**Comment by mattfarina** [comment]
I can add a little detail.

When you run commands like `glide up` use the `--use-gopath` flag. For example,

```sh
$ glide --use-gopath up
```

This will tell Glide to check for a package in the `GOPATH`. If it's there, has the same `repo` as the one we're asking for, and isn't dirty (uncommitted changes) then copy it to the `vendor/ folder`. Once in the `vendor/` folder the package will be updated and the version will be set to the one in the Glide configuration.

There are also the `--cache` and `--cache-gopath` flags. The `--cache` flag tells Glide to cache dependencies in the `~/.glide` folder. This keeps them out of the `GOPATH` but keeps a repo copy locally. The `--cache-gopath` puts any dependencies found in the `GOPATH`. This can be useful in combination with the `--use-gopath` flag.

All caching is currently opt-in. Depending on your network connection, disk speeds, and tree complexity it may be less performant to use the cache. This is something you should test for your situations.

Does that help?

**Comment by jeffellin** [comment]
This is very helpful.  Do you know what happens when you specify a version in the glide.yaml?  Will the version be checked when using the --use-gopath flag?

**Comment by mattfarina** [comment]
When a version is set in the `glide.yaml` file that version will be set. It's not checked when the copying happens. Instead, it makes sure it's the same vcs repo. If so, it does an update after copying. Then it explicitly sets the version (or in the case of a SemVer range it finds and then sets the version).

It explicitly sets versions rather than assuming something is at the right version.

**Comment by jeffellin** [comment]
Then it explicitly sets the version

Are you referring to what is set int he lock file?

**Comment by mattfarina** [comment]
When `glide update` or `glide get` are run it explicitly sets the version based on what's in the `glide.yaml` file. When `glide install` is run it explicitly sets the version based on what's in the `glide.lock` file.

If you run `glide up --use-gopath` with no version set in the `glide.yaml` file you could get some unexpected results because the version will relate to the GOPATH. I would always specify a version, even if it's a branch.

**Comment by jeffellin** [comment]
Thanks a lot for the information, it has been very helpful.  Is this in the docs somewhere and I missed it?

**Comment by dmitris** [comment]
> $ glide --use-gopath up

I believe it's the other way around: glide up[date] --use-gopath

From `glide help update':
```
OPTIONS:
   --use-gopath			Copy dependencies from the GOPATH if they exist there.
```

**Comment by mattfarina** [comment]
@dmitris you're right. Thanks for the correction.

**Comment by mattfarina** [comment]
The cache is not a default thing that just works (no on/off) flags. If there are continued questions or issues with the cache please open an issue.
