### ISSUE TITLE
Refactor and remove Cookoo

### ISSUE THREAD

**Issue by technosophos** [Masterminds/glide#181]
The following still need to be update.
- [x] Get
- [x] Install
- [x] Update
- [x] Import GPM
- [x] Import Godep
- [x] Import GB
- [x] Create
- [x] Remove

**Comment by mattfarina** [comment]
I believe Install is complete. Tested it with both vendored and non-vendored. Though, I didn't test all permutations of all options.

**Comment by mattfarina** [comment]
I read the Create code and ran some tests. It appears to be working.

**Comment by mattfarina** [comment]
While importing from godep appears to work the functionality is odd now that the create command can auto-import and you already need a `glide.yaml` file to run the command (which is how it worked before the update).

@technosophos should we revisit how the import commands work?

**Comment by mattfarina** [comment]
Tested importing gb and it appears to work. Again, the import functionality is still confusing. But, that's there today. The import combines what's in the `glide.yaml` file with the imported GB contents and displays them rather than saves them. For example, if the `glide.yaml` file has been created and has no dependencies and you import from GB it will only print to the screen what was in the GB file. But, if you used `glide init` to create the yaml file and it picked up projects not listed in the GB manifest those additional ones will be included in the print display.

https://github.com/hypocenter/webgetter is a project you can see this in action on.

**Comment by mattfarina** [comment]
Tested GPM import which is working.

**Comment by mattfarina** [comment]
Just reviewed the Update commands needs some work. Right now it does a single pass and does not handle imports. If the initial dependencies aren't present it can't get their dependencies. In the dependency tree it's only able to resolve a couple steps and not the complete tree. And, it can't handle imports from other package managers.

**Comment by mattfarina** [comment]
We still have an open todo to fix up dependency handling inside the installer. It goes between deps, string names, and deps where some info can be lost along the way. For example, subpackages aren't showing up in lock files along with other info.

**Comment by mattfarina** [comment]
This is closed with the merger of #222.
