### ISSUE TITLE
`glide up TARGET` creates wrong lock file

### ISSUE THREAD

**Issue by technosophos** [Masterminds/glide#186]
If I specify a target on `glide up`, the lockfile that is generated is only partial.

Steps to reproduce:

1. Clone github.com/helm/helm
2. wc -l glide.lock
3. glide up github.com/Masterminds/sprig
4. wc -l glide.lock

Glide >0.8.2

**Comment by mattfarina** [comment]
The [packages being updated](https://github.com/Masterminds/glide/blob/b07f081dfd5cf1714bd60f6fba91f900003c38be/glide.go#L616) are passed into [Flatten](https://github.com/Masterminds/glide/blob/b07f081dfd5cf1714bd60f6fba91f900003c38be/cmd/flatten.go#L40) for `up`. My first thought is the problem is there.

**Comment by mattfarina** [comment]
@technosophos in addition to fixing this I added errors and warnings if there are missing packages (not being updated) that would cause a bad glide.lock file to be generated.
