### ISSUE TITLE
Switch to go.tools/go/vcs

### ISSUE THREAD

**Issue by technosophos** [Masterminds/glide#2]
It would probably be good to use the Go Tools VCS library if possible:

http://godoc.org/code.google.com/p/go.tools/go/vcs

**Comment by mattfarina** [comment]
`go/tools/vcs` turned out to be a limiting package. For example, using it there was no easy way to checkout branches. It is designed to do what `go get` needs and isn't really extensible beyond that. So, I created `github.com/masterminds/vcs` that attempts to create a unified interface across VCS. Using that instead.

You can see this starting in version 0.5.0-beta1
