### ISSUE TITLE
Glide now scans all dependencies for their dependencies and tries to install them.

### ISSUE THREAD

**Issue by DocMerlin** [Masterminds/glide#207]
Glide now scans all dependencies for their dependencies and tries to install them.  This breaks glide for many packages, by trying to install large number of unused dependencies.  
It also breaks certain other packages by trying to install at a root level, certain dependencies that are handled internally.
Could you guys go back to the old system?
I was excited about having a go package management system that worked, but it now no-longer works for the dependencies I need. 

:-(

**Comment by mattfarina** [comment]
I understand your pain point. We're not going back to the old system but we'll move to something better than the old system and what's there now. Let me explain.

If Glide only fetches what's listed in the `glide.yaml` file you need to have the complete tree of dependencies listed there. That's your projects dependencies, the dependencies of your dependencies, etc. This is hard to keep track of especially when you bring version support to the table. Each project should manage their own dependencies. This is how every other major package manager in every language works for good reasons.

But, Glide is fetching all possible dependency chains rather than the ones being used. This can lead to too many dependencies being fetched. Previous Glide didn't fetch all the dependencies. Now it fetches everything possible. At some point soon we will update the resolution to pull the paths in use rather than all of them. To try and find the useful middle ground.

**Comment by termie** [comment]
this is marked a duplicate, but of what?

I am running into this in a huge way, anything that tangentially mentions Docker pulls in 500MB of dependencies.

**Comment by termie** [comment]
related,  i think coreos/go-systemd might mention docker somewhere (the two private repos don't) and I end up with 733MB worth of deps (was 132MB on glide 0.2) https://gist.github.com/termie/885e092351be6951a734

**Comment by mattfarina** [comment]
I removed the duplicate label because I can't find the other issue.

The gist, there is a feature request to only follow the package paths being referenced rather than to get all the things.

**Comment by termie** [comment]
@mattfarina i will happily write that for you do you have some pointers on where to start? spending 10 hours on this will save me 2 - 20 minutes 15 times a day

**Comment by termie** [comment]
k, after spending a couple hours tracing code through the "cookoo.Registry" and get_imports.go, my conclusions (and heap of unsolicited advice, no offense meant just being direct with my opinionated observations) are: 
 1. I can add a single line to my glide.yaml and turn off recursion altogether to end up with a 24MB vendor folder (vs 733MB) since there is only a single subdependency that needs to be pulled in (vs what seems like 100 that are attempted with recursion on)
 2. you're kind of bypassing the point of having a static type system by using your homerolled cookoo library, the compiler can't do anything at all to help you and you're expecting other devs to learn a whole new DSL to do the equiv of packages := options.Packages
 3. you've put almost all your code in the cmd subpackage, which kind of defeats the point of the subpackage since it doesn't really separate the code that defines commands and command structure from the code that is core to glide (updating things from vcs, looking for dependencies), and the command structure code is almost completely in the "routes" command (despite codegangsta/cli being included)

there is probably a situation where it is nice to recurse all these dependencies, but in every case for our existing projects doing a `glide install --no-recursive` followed by a `go build` listed the 1 or 2 deps that we needed to add to glide.yaml to have the project build. With that in mind, a `glide freeze` command seems useful to output what would be the contents of glide.lock based on what version of things i have in vendor (i feel like i saw such a command before but i can't find it anymore)

**Comment by termie** [comment]
i guess the question to ask is, what does `go build` know that we don't when it tells us we are missing a dependency and how do we do that ourselves

**Comment by mattfarina** [comment]
@termie We have a `feat/no-cookoo` branch we're actively working to clean up the architecture. The things you noted, like the `cmd` sub-package are something we're in flight on fixing.

As part of that we have a fairly new dependency resolver. It was initially designed to scan directories which is needed for a root project. The Go code could reside in the top level folder or start in subdirectories. We need to handle that.

Once we know package paths things need to be handled a little different. Rather than scan entire codebases we can follow full package paths. We need a dependency handler to do that.

If you give us a few more days (to sometime next week) I hope to have the rework back on master and we can start to tackle this a little better.

**Comment by termie** [comment]
@mattfarina cool, those all sound like good ideas :+1: I didn't get deep enough into how the build context was deciding on packages to know what needs to be done (I started by doing top level deps only, then when I tested to see how many were still being complained about and only saw 1 missing dep I shortcircuited my patch).

**Comment by mattfarina** [comment]
I just did some more work on the new architecture branch. I "should" be able to merge it in the middle of next week. We have one glaring issue left I'll fix I can fix before then.

**Comment by mattfarina** [comment]
This has been worked on by @technosophos and we'll be merging it in soon. See #240.

**Comment by mattfarina** [comment]
Glide, on master right now, only walks the import tree being used and imports the needed packages. There is a flag to get all things if that is still desired. With that I'm going to close this issue. If there is a problem with the new functionality please let us know.
