### ISSUE TITLE
config api inconsistency import vs devImports

### ISSUE THREAD

**Issue by james-lawrence** [Masterminds/glide#217]
not sure if we care but noticed that the two configuration directives import and devImports have different plurality.

be nice if they were consistent when devImport is implemented.

**Comment by mattfarina** [comment]
@james-lawrence fantastic catch. When we make `devImport` work, in the near future, we can fix this.

**Comment by mattfarina** [comment]
I think I found what's going on. There are two files with slightly differing formats. In the `glide.yaml` file it's `import` and `devImport`. In the `glide.lock` file it's `imports` and `devImports`.

Since the lock file shouldn't usually be manually altered (it's being rewritten by Glide each time `glide up` it run) this should be ok. It's not perfect but it should be ok.
