### ISSUE TITLE
Vendor package which has vendor and Godeps directories under package root.

### ISSUE THREAD

**Issue by zh-lab** [Masterminds/glide#232]
When I try to vendor testify package, I found that glide tries to import configuration from Godeps.
```
[INFO] Found Godeps.json file.
[INFO] Found Godeps.json file for "github.com/stretchr/testify"
```
But in fact, testify already has a vendor directory.

It seems that glide does not handle this situation or just my misunderstanding?https://github.com/Masterminds/glide/blob/master/importer/importer.go#L36

And, is there possible to provide a cleanup command or flag to remove directory such as _workspace under Godeps?
Directory like _workspace may have lots of useless code.

testify: https://github.com/stretchr/testify

**Comment by mattfarina** [comment]
@zh-lab Good questions.

1. Glide will import packages but does not alter the contents of a repo it imports. Right now Glide pulls down VCS repos. If the contents of them are altered it makes the repo dirty and difficult to switch versions.
2. Libraries, that is non-main applications, really should not have a `vendor/` folder unless there is a specific known reason. There are a couple reasons for that and Glide attempts to flatten the tree to solve them.
    * If another package imports the same dependency in a different `vendor/` folder it will end up in the compiled binary twice. Each location the dependency is imported is a different location to import. Before of this the discussions in the Go community have lead to the understanding that you should have the `vendor/` folder at the app level unless you have a specific reason not to. Is that the case with testify?
    * Instances of a type created with a package in one `vendor/` folder are not compatible with the same package in other `vendor/` folders. If you try to pass instances around you get errors. [Here's an example](https://github.com/mattfarina/golang-broken-vendor)
3. Since the `vendor/` location for packages like testify will be used even if Glide flattens the tree we can likely add an optimization to not fetch the code again and provide a message. This part of the resolver code is being worked on right now so I'll wait for that work to be completed before I look into this.

**Comment by zh-lab** [comment]
@mattfarina 
Package like testify has its own vendor. If we do not want to use testify's vendor content, we should delete its vendor. But this make the repo dirty. What should we do for this case?:flushed:

**Comment by technosophos** [comment]
1. We will not do anything to computationally alter a package. It's a mess. We then have to do all kinds of VCS-specific operations, many of which are error prone.
2. However, unless a project imports the `vendor/` path explicitly (like etcd does), we have to treat it like a global dependency in order to allow other packages to interoperate. (@mattfarina has an example of this problem somewhere)
3. And in one very weird edge case, we cannot programmatically alter certain repos without impacting the license state of your code (viz LGPL -- if you remove any part of their code, it's an alteration, and hence you have to release your code under LGPL)

So for the time being, we are not going to change this behavior at all. We'll just accept the fact that some packages will include files that don't get used.

However, we'd appreciate it if others filed issues against packages that check their dependencies in. It adds bloat for all of us when they do.
