### ISSUE TITLE
Oops! Command glide-build does not exist.

### ISSUE THREAD

**Issue by hyper-carrot** [Masterminds/glide#239]
Hi,

I created a project and created glide.yaml by `glide init`, but I got an error when I build use `glide build`:
```
Oops! Command glide-build does not exist.
```

Who can explain?

btw: I installed glide vie `brew install glide`.

**Comment by mattfarina** [comment]
@hyper-carrot Glide does not have a build command. What are you trying to do?

Glide manages dependencies. You use the `go` tool to build, run, or otherwise work with your code. Glide complements that.

I recently wrote up a [getting started guide](http://glide.readthedocs.org/en/latest/getting-started/) that might help.

**Comment by hyper-carrot** [comment]
@mattfarina OK, I see. I wanted to build the project code like `gb build`.I solved it by using `go build`. Thank you.
