### ISSUE TITLE
glide get github.com/Azure/go-autorest/autorest fails

### ISSUE THREAD

**Issue by colemickens** [Masterminds/glide#287]
Steps:
* Removed `glide.lock`.
* Removed `vendor/`.
* Execute `glide get github.com/Azure/go-autorest/autorest`

Expected, it works.

Actual, it fails:

```
$ glide get github.com/Azure/go-autorest/autorest
[INFO] Preparing to install 1 package.
[INFO] Importing github.com/Azure/go-autorest
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/Azure/azure-sdk-for-go.
[INFO] Fetching updates for github.com/golang/glog.
[INFO] Fetching updates for github.com/spf13/cobra.
[INFO] Fetching updates for github.com/pborman/uuid.
[INFO] Fetching updates for github.com/Azure/go-autorest.
[INFO] Resolving imports
[INFO] Fetching updates for github.com/spf13/pflag.
[INFO] Fetching updates for github.com/Azure/go-autorest.
[INFO] Fetching updates for golang.org/x/crypto.
[INFO] Fetching updates for github.com/dgrijalva/jwt-go.
[ERROR] Error scanning github.com/Azure/go-autorest/azure: open /home/cole/code/azure/azkube_gopath/src/github.com/colemickens/azkube/vendor/github.com/Azure/go-autorest/azure: no such file or directory
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/Azure/azure-sdk-for-go.
[INFO] Fetching updates for github.com/pborman/uuid.
[INFO] Fetching updates for github.com/golang/glog.
[INFO] Fetching updates for github.com/spf13/cobra.
An Error has occured
```

I don't know where `glide` came up with this import path in the ERROR line. It's simply wrong: `github.com/Azure/go-autorest/azure`. (Note it's missing the `autorest` segment between `go-autorest` and `azure`.)

It seems to have gotten confused, I'm guessing because the "top package" is not at the top of the repo.

`glide` is from whatever is on master at this very instant (bff8b50d232e5005b452de18d54ca7439c596415).

Any advice for unblocking would be greatly appreciated.

**Comment by colemickens** [comment]
Also, when I execute that, the yaml it inserts is this:

```
- package: github.com/Azure/go-autorest
  subpackages:
  - autorest
```

which also seems wrong. `go-autorest` is not a package, just a repo.

**Comment by colemickens** [comment]
But correcting it to:
```
- package: github.com/Azure/go-autorest/autorest
  subpackages:
  - azure
```

doesn't help either. (And I need the azure subpackage as well).

**Comment by colemickens** [comment]
False alarm. I had the wrong import path in my code (which is where glide got it).

Error message is a bit confusing though. Something could hint me towards checking my source rather than a glide file.

(In fact, I don't even expect glide to be scanning my code at this point... why is it? Why is this error coupled to the `glide up` process even though it successfully pulled down the repo and wrote the `glide.lock` file.)

**Comment by mattfarina** [comment]
@colemickens I'm glad this was a false alarm. We're really open to better error messages as well. I'll have to think about it here.

Once you hit `Resolving imports` Glide is scanning code. This happens in two possible ways:

1. Glide reads the imports from a package to know about other imports to look at. The `go/build` package is used to do this. That package reads the code up through the `import` declaration to parse the imports.
2. There are rare cases where a directory will have multiple packages. When Glide reads the `.go` files it skips `+build` flags so it can fetch dependencies for all environments rather than the one Glide was run in. If Glide encounters multiple packages it falls back to scanning the code to discover the build tags used and then scans based on the different permutations to build a list.

Hope this helps.

In the next major release we'll see if we can put a better message here.

**Comment by mattfarina** [comment]
I've tinkered with ways to handle this and none of it makes me happy. Pushing out another release.
