### ISSUE TITLE
glide get -u doesn't do what I expect

### ISSUE THREAD

**Issue by thockin** [Masterminds/glide#310]
I (perhaps naively) expected `glide get -u` to update a dep to the head of whatever VCS, copy it into my vendor/ tree, and update my local metadata.  Instead I get:

```
[INFO] Preparing to install 1 package.
[WARN] Package "github.com/coreos/rkt" is already in glide.yaml. Skipping
```

What am I misunderstanding?  As far as I can tell, the -u flag doesn't do anything at all.

**Comment by jackspirou** [comment]
You might want to take a look at https://github.com/govend/govend.  It acts like `go get`.

**Comment by technosophos** [comment]
You expected correctly, @thockin. We need to check whether that's a bug or a spurious message.

**Comment by technosophos** [comment]
I misspoke earlier. Instead of using `glide get` to update, we use `glide up`. You can trick `glide get` into doing updates, but we have been trying to segregate true update functionality into the dedicated `glide update` command. (`glide get -u` does something different than `go get -u`. We probably shouldn't have done that.)

That said, I think we might have an issue.

Given this, `glide up PKG` should fetch the most recent version that adequately matches the version requirements in `glide.yaml`.

Consider `glide.yaml` has something like this:

```yaml
package: technosophos.com/x/pkgtest
import:
- package: github.com/Masterminds/sprig
  version: 1.1.0
```

This should pull _exactly_ version 1.1.0. And it does. And if I want to make that directive more flexible, I can add SemVer ranges (e.g. `version: ^1.1`). That all works.

But if I delete the `version:` field (or never add one in the first place), then any checkout will satisfy the version rule. It appears that in some cases, a package will hit this state and will NOT be updated during a `glide up`.

So if I change the above YAML to this:

```yaml
package: technosophos.com/x/pkgtest
import:
- package: github.com/Masterminds/sprig
```

And then do `glide up`, looking at the Git log for Sprig shows me this:

```
commit 2493695b1e81bd6ef2ac18d2591fcf46725e5a50 (HEAD, tag: 1.1.0)
```

That's not what I expected. I expected it to run to the tip of master.

If I add `version: master` into the YAML file, then do `glide up`, then check Sprig's git log, I see the head is this:

```
commit fd057ca403105755181f84645696d705a58852dd (HEAD, tag: 1.2.0, origin/master, origin/HEAD, master)
```

That is what I would have expected from an empty version. I suspect that somewhere in the 0.9 tree, we made a "performance fix" that introduced this behavior (or we're missing a `SetVersion()` on packages that don't declare a version). Or it could be that we did this intentionally in the name of caution. Any thoughts on this @mattfarina ?

**Comment by thockin** [comment]
I see.  You should document that `glide get -u` != `go get -u` especially since it talks about updating vendored code :)
