### ISSUE TITLE
Update a particular package

### ISSUE THREAD

**Issue by Unknwon** [Masterminds/glide#321]
Hi,

How to only update a particular package and remain others with current version? `glide get` seems always recreates the glide.lock file and fetches the latest version of everything.

**Comment by technosophos** [comment]
This is the reason we check all dependencies when updating one. More than one package may depend on the package you are updating. So we have to scan all of the other packages to see whether they depend on the package you've updated. Then we may need to re-negotiate the versions of shared packages because of this.

In order to make sure that we can re-negotiate correctly, we have to fetch all of the repository updates even if we don't change the actual version that is locked.

If you _really_ want to just update one dependency, you have to do this manually by going into vendor/ and running the right VCS operation. However, this may leave your other dependencies broken.

**Comment by Unknwon** [comment]
Thanks for the response!
