### ISSUE TITLE
`glide up` - Removed dependencies don't get removed from lock file.

### ISSUE THREAD

**Issue by andradei** [Masterminds/glide#335]
Is this the intended behavior?

Shouldn't removing a dependency from `glide.yaml` be reflected on `glide.lock` with `glide up[date]`?

**Comment by andradei** [comment]
Also, should `glide rm` remove the package from the _vendor/_ directory as well as the `glide.yaml` entry?

**Comment by technosophos** [comment]
Is the package still referenced in the code? The `glide.lock` file will have the referenced package there if something is still importing it. (Otherwise, you may have found a bug.)

By default, I think we decided not to remove stuff from `vendor/`. I believe you have to pass `--delete` to delete the files. Like `glide up --delete`

**Comment by andradei** [comment]
You're correct about the imports in code affecting the decision in `glide.lock`.
Thanks for `glide up --delete` I haven't found that switch option until `glide up --help`.

This is a great project.
