### ISSUE TITLE
Ignores not working with relative imports

### ISSUE THREAD

**Issue by tmm1** [Masterminds/glide#359]
```
$ cd /tmp
$ git clone https://bitbucket.org/snippets/tmm1/krGBM glidetest

$ cd glidetest

$ ./bootstrap.sh
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/gin-gonic/gin.
[INFO] Resolving imports
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for /tmp/glidetest/one.
[WARN] Unable to checkout /tmp/glidetest/one
[ERROR] Update failed for /tmp/glidetest/one: Cannot detect VCS
[ERROR] Could not update packages: Cannot detect VCS
```

**Comment by tmm1** [comment]
Was hoping this would be fixed with #354, but I confirmed it's still not working in glide 0.10.1

**Comment by technosophos** [comment]
What's your $GOPATH set to? `/tmp/glidetest/one` does not look like a valid GOPATH

**Comment by tmm1** [comment]
You can see in the `bootstrap.sh`, I set `GOPATH=$(pwd)/vendor`. This approach works great for regular local imports, but there seems to be an issue when one subpackage tries to import another using the `../` prefix (there is no issue with `./` imports).

**Comment by technosophos** [comment]
For the Go tools, as of 1.5, you need to set the GOPATH correctly. Otherwise the built-in vendor logic does not work. Glide simply uses the Go libraries for this.

**Comment by technosophos** [comment]
Oh, interesting... I'm looking at your PR.

**Comment by ches** [comment]
@tmm1 I can't access your repo/snippet thing, but I assume it deals with the fact that `GOPATH=$(pwd)/vendor` would expect things to be under a `src` subdir of `vendor`, which Glide doesn't?

Not to disparage Glide on it's own project space, but I quite happily used `gb` for that kind of workflow on private application projects. The downside is those projects are not `go get`-able so it's not very tenable for published library projects, so that's where Glide is promising to me.

**Comment by tmm1** [comment]
Oops, I thought I had made it public. It is now.

`gb` looks interesting, but I didn't want to have to stop using `go build` and other standard commands (especially when they're generally being invoked by Atom plugins and other tools).

Anyway, this issue has been resolved with https://github.com/Masterminds/glide/issues/361 and things are working quite well for me with that patch.
