### ISSUE TITLE
Honor build constraints

### ISSUE THREAD

**Issue by raphael** [Masterminds/glide#375]
It looks like `glide` does not honor build constraints when parsing imports. As of a few hours ago this is going to cause anyone using the [context](https://godoc.org/golang.org/x/net/context) package (or using a package that uses it) to get the following error when running glide:
```
[WARN] Unable to checkout context
[ERROR] Update failed for context: Cannot detect VCS
[ERROR] Could not update packages: Cannot detect VCS
```
This is caused by this file:

https://github.com/golang/net/blob/master/context/go17.go

As you can see it imports the stdlib `context` package which is only available in go 1.7...

**Comment by rschmukler** [comment]
This is a duplicate (more generically) of #373

**Comment by mattfarina** [comment]
Glide doesn't honor build tags because it's trying to resolve the complete cross platform dependency tree. The dependencies may span multiple go versions, operating systems, and so forth. If only one platform had their tree vendored or only the dependencies for particular environment were locked it would cause problems in other environments. Especially in the windows vs linux setups where it's common to use build tags to separate work.

For #373 I'll have a fix in the next day. I'm marking this as a duplicate and closing in favor of that issue.

**Comment by raphael** [comment]
Thank you, makes sense.
