### ISSUE TITLE
support specify depth and branch to speed up git clone

### ISSUE THREAD

**Issue by medcl** [Masterminds/glide#405]
Hi,
will glide support specify the depth of  `git clone` repo , the clone process will be more faster

`git clone git://github.com/medcl/my.git -b master --depth 1`

many thanks!

**Comment by sdboyer** [comment]
Probably not, because using shallower clones decreases performance significantly in the longer term.

https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193772935

**Comment by mattfarina** [comment]
@medcl For two reasons we cannot do this.

1. For later updates it will be slower. See the link from @sdboyer.
2. We will not have enough data to resolve [versions](http://glide.readthedocs.io/en/latest/versions/). This is only useful if you are getting the tip of the default branch.

**Comment by medcl** [comment]
leave a option and let user to choose will be better, if the repo with a lot of commits, and update is not such a frequent operation, i'd like to fetch a small but full content

**Comment by sdboyer** [comment]
Providing a choice to the user about how the repositories are cloned could make correct operation of the tool difficult, if not impossible. We take whatever steps we can to ensure the minimum amount of network activity.

Efforts to further optimize and reduce network activity would be welcome, of course - you'd need to dig into the code and find ways of doing so that don't break other things.

**Comment by medcl** [comment]
@sdboyer i understand what you mean about reduce network activity, for some case i can reduce network and fetch diff commits, but if i am using in CI environment, we clean up first and then fetch the remote repo content, so it will be heavy and take really a long time for preparing the build every time, that's the pain.

**Comment by sdboyer** [comment]
CI environment's aren't an easy question - particularly the disposable ones provided by most of the CI services. If you spin up from nothing every time, then there's no question that the costs can get high.

It *might* be feasible to have a param that, on `install` (and ONLY `install`), makes the choice to use shallower clones. That's one approach. However, it's still generally slower than grabbing tarballs when they're made available by the upstream source (which github does). And that's probably slower still than using things like, say, CircleCI's disk caching mechanism to carry pre-cloned repos between builds. Most importantly, though, those approaches don't potentially compromise the correctness of the system in the same way that messing with git clones does.

**Comment by mattfarina** [comment]
@medcl I have a couple questions for you. CI environments are a target for us and we do want to speed things up there. It's just complicated to do that well and meet all our use cases.

1. Do you use `glide update` or `glide install` in your CI environment?
2. Do you checkin your `glide.lock` file?
3. Where do most of your dependencies come from? GitHub.com and Bitbucket.org? Someplace else you can share?

I'm all for speeding things up and I've talked with (and will again) those at GitHub about this. I have some ideas other than a shallow clone I'd like to pursue and your input will help.

**Comment by medcl** [comment]
@mattfarina Thanks, to  your question:
1. I use `glide update  --no-recursive` in my Makefile
2. I dont have the `glide.lock` checkin
3. only Github.com

Hope that helps.

**Comment by sdboyer** [comment]
@medcl checking in the `glide.lock` is really a strongly-preferred method of operation. Particularly in the Go ecosystem, you get very little no build reproducibility without it.

It also allows considerable performance boosts (though I can't recall offhand if `glide install` has those implemented right now). When you have no lock file, glide has to recompute a lock file on the way to installation. That necessarily means it has to clone repositories, in order to get the version information contained therein. If, however, you have a lock file, and the upstream source is something like github.com that offers tarball downloads for refs, then it's possible for glide to skip the clone altogether and just grab tarballs.

**Comment by medcl** [comment]
@sdboyer Thanks, i will try to use `glide.lock`

**Comment by yanyiwu** [comment]
checking in glide.lock should be written in README.md, when I use this project  at first, i can not figure out glide.lock is needed to be checked in. And i find nothing about it in README.md.

**Comment by sdboyer** [comment]
@yanyiwu yeah, I just looked through, and it's...implied, at best. Seems like something that should probably be stated more clearly.

To be clear, there *are* use cases for not checking in `glide.lock`...but my goal, at least, is to reduce that set to nonexistence.
