### ISSUE TITLE
directory

### ISSUE THREAD

**Issue by pb-cdunn** [Masterminds/glide#502]
Which directory should the commands be run in? It's not clear from the docs. We need to see a simple `cd` somewhere.

It *seems* like we are supposed to run in a GOPATH directory, which leads to my real problem.

I see this tree in the **glide** docs:
```
- $GOPATH/src/myProject (Your project)
  |
  |-- glide.yaml
  |
  |-- glide.lock
  |
  |-- main.go (Your main go code can live here)
  |
  |-- mySubpackage (You can create your own subpackages, too)
  |    |
  |    |-- foo.go
  |
  |-- vendor
       |-- github.com
            |
            |-- Masterminds
                  |
                  |-- ... etc.
```
That indicates we will end up with vendor packages in `$GOPATH/src/myProject/vendor/*`. Great! That's what I want. But that doesn't happen for me. I ran this:

    cd $GOPATH
    glide --verbose get -s github.com/user/projX

And I ended up with `$GOPATH/vendor/github.com/user/projX`. That is *not* how I had interpreted the docs, and it is *not* what I want. I plan to put dependencies into `$GOPATH/src/github.com/me/myProj/vendor/*`, and I was hoping that **glide** could help me with that.

What am I doing wrong?

**Comment by pb-cdunn** [comment]
I'll tell you why I have so much trouble with the entire GoLang universe. I am building within an enterprise. For reasons beyond my control, our automated process will pull all dependencies first, and then build. There is no iteration between building and fetching. It's just 2 steps:

1. Fetch all source code.
2. Build (in topological order).

The easy solution would be relative imports, but the Go authors seem to think I'm an idiot for wanting that. So that's a non-starter.

The `vendor/` directory can solve a lot of problems for me. But I need a way to copy things into it. I might have to do it manually. But whenever I add a new dependency, and its dependencies, and their dependencies, *ad nauseum*, it's a lot of work. I really need a tool which can do that for me.

I can remove the `.git` directories myself. I honestly don't understand why people request such trivial features. The hard part is acquiring all the repositories recursively.

I hope that makes sense. Any suggestions?

**Comment by sdboyer** [comment]
It sounds like all your expectations of glide are the right ones. I *think* all your woes should be solved by doing this instead:

> ```
cd $GOPATH/src/github.com/me/myProj
glide --verbose get -s github.com/user/projX
```

The key is that glide is always operating relative to a single project, rather than the global mess that is `$GOPATH`. And it infers that project by walking back up the tree from cwd to find a `glide.yaml`.

Now, I don't fully follow what this means:

> For reasons beyond my control, our automated process will pull all dependencies first, and then build. There is no iteration between building and fetching. It's just 2 steps:

But hopefully, this'll solve your problem. Once you move to that directory, glide should (on most commands) recursively walk, resolve, and fetch transitive deps into your desired vendor dir.

**Comment by pb-cdunn** [comment]
```

**Comment by pb-cdunn** [comment]
```sh
$ glide --verbose get -s github.com/gyuho/goraph
[WARN]  The name listed in the config file (.) does not match the current location (src/hgapg)
[INFO]  Preparing to install 1 package.
[INFO]  Attempting to get package github.com/gyuho/goraph
[INFO]  --> Gathering release information for github.com/gyuho/goraph
[INFO]  The package github.com/gyuho/goraph appears to have Semantic Version releases (http://semver.org).
[INFO]  The latest release is v2.0. You are currently not using a release. Would you like
[INFO]  to use this release? Yes (Y) or No (N)
n
[INFO]  --> Adding github.com/gyuho/goraph to your configuration
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching updates for github.com/gyuho/goraph.
[INFO]  Resolving imports
[ERROR] Failed to build an initial list of packages to scan: lstat ../../hgapg: no such file or directory
[ERROR] Failed to resolve local packages: lstat ../../hgapg: no such file or directory
```
I guess I'm expected to `glide add` my own project first. That's annoying because I use my own revision-control system to obtain my own package.

> For reasons beyond my control, our automated process will pull all dependencies first, and then build. There is no iteration between building and fetching. It's just 2 steps:

I have to use *something* to acquire source code before anything else happens. I *cannot* run **go get** at that point because **go** has not yet been installed and built. Folks have decided that we must have *all* source code (including **gcc** and **go**) before we being to build anything, as a pre-condition for ISO Compliance for govt/medical work. It annoys me, but that's life.

My solution is to put all dependencies into a single repo, which I can obtain via `git clone`. I want to use **glide** to populate my `vendor/` directory. Then, people can actually run `go get` on my own project, and I can also build it internally without using `go get` at all. You see, our internal build is ISO Compliant, but we also make our source code freely available for external builds.

**Comment by pb-cdunn** [comment]
I have `src/hgapg/`. That's my tree within GOPATH. I have no idea how to `glide get` that, but it's already there, so I don't need to interact with github. What should my `glide.yaml` look like?

**Comment by sdboyer** [comment]
> What should my `glide.yaml` look like?

From what I can quickly glean from these error messages, `package: hgapg` is all you should need to change in your `glide.yaml`. Then glide knows how to interpret local imports within your project (e.g. `hgapg/foo` imports `hgapg/bar` - both are below the named project root, so glide knows not to go looking for them).

While the particular reasons for the build constraints you have to adhere to might be unique, the upshot is a pretty common use pattern, I think. You commit your `glide.lock`, and also your `vendor/`, which makes the system `go get`-able, but also fetchable with nothing more than git.

**Comment by pb-cdunn** [comment]
```sh
$ cd src/hgapg
$ glide --verbose get -s github.com/gyuho/goraph
...
[ERROR] Failed to build an initial list of packages to scan: lstat ../../hgapg: no such file or directory
[ERROR] Failed to resolve local packages: lstat ../../hgapg: no such file or directory
$ cat ../../glide.yaml
cat: ../../glide.yaml: No such file or directory
```
Oh! Maybe that's the problem. My `hgapg` is actually a symlink, so there is no `../../glide.yaml`. I'll try replacing the symlink and post again in the morning. Thanks!

**Comment by pb-cdunn** [comment]
Well, I dropped the symlink, and then **glide** worked like a charm. But that's very tough since I do not control how the source-code is obtained. The repo goes where it goes. I had used a symlink to create a Go workspace to build in.

So instead, I have moved all the Go code under a `src/` directory in my repo itself. Now, the repo root-dir is on GOPATH, and I run **glide** from that directory. It fails this way:
```sh
glide --verbose get -s github.com/gyuho/goraph
[INFO]  Preparing to install 1 package.
[INFO]  Attempting to get package github.com/gyuho/goraph
[INFO]  --> Gathering release information for github.com/gyuho/goraph
[INFO]  The package github.com/gyuho/goraph appears to have Semantic Version releases (http://semver.org).
[INFO]  The latest release is v2.0. You are currently not using a release. Would you like
[INFO]  to use this release? Yes (Y) or No (N)
n
[INFO]  --> Adding github.com/gyuho/goraph to your configuration
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching updates for hgapg/foo.
[INFO]  --> Fetching updates for github.com/gyuho/goraph.
[WARN]  Unable to checkout hgapg/foo
[ERROR] Update failed for hgapg/foo: Cannot detect VCS
[ERROR] Failed to checkout packages: Cannot detect VCS
make: *** [glide] Error 1
```
You can repeat that yourself easily:
```sh
git clone git://github.com/pb-cdunn/hgapg
cd hgapg
git checkout -t origin/glide
glide init
make glide #which sets GOPATH for you
```
Is there a way to convince **glide** to ignore the VCS (aside from downloading)?

**Comment by sdboyer** [comment]
> But that's very tough since I do not control how the source-code is obtained.

I don't understand what you're expecting to control here.

> So instead, I have moved all the Go code under a `src/` directory in my repo itself.

This is not the intended use pattern. Maybe it could work...but I don't see what problem you're trying to solve, per the previous. It does kinda sound like you might be fighting some basic Go toolchain requirements more than glide's own.

> You can repeat that yourself easily:

Neither a branch nor a tag named glide is present in github.com/pb-cdunn/hgapg (as of a couple seconds ago), so I can't replicate.

**Comment by pb-cdunn** [comment]
> Neither a branch nor a tag named glide is present in github.com/pb-cdunn/hgapg (as of a couple seconds ago), so I can't replicate.

Oops. It's there now.

> I don't see what problem you're trying to solve.

I do not control how source-code is pulled from the web. I just use it from a given directory. `go install` expects a particular directory structure, so I have only a few choices:

1. Put that `src/` directory structure into the repo;
2. Symlink the repo into `src/`; or
3. Copy (or clone?) the repo into a workspace after it has been downloaded.

I guess the last one would work with **glide**.

**Comment by sdboyer** [comment]
> I do not control how source-code is pulled from the web.

What kind of "control" are you expecting to have? 

Are you expecting that glide just provides a list of repos to clone, and you write a script that then clones them into a place that you decide? Or, something else?

**Comment by pb-cdunn** [comment]
I expect to control the VCS operations myself. I only want glide to obtain and update the dependencies.

Don't worry. You're operating within the GoLang ecosystem. I'm not criticizing your architecture at all. I'm just trying to find something that works.

I really like glide's support for "locking" versions, so I can update easily later. But if I can't use glide in my own use-case, that's ok. You've been very helpful. Thank you.

**Comment by sdboyer** [comment]
> I expect to control the VCS operations myself. I only want glide to obtain and update the dependencies.

If "VCS operations" refers to checkout/commit/branch switching on *your* project, then yes, you have complete control. If it refers to granular control about how your project's *dependencies* are checked out, then...well, I think you'll be hard-pressed to find any tool that allows that kind of control. It sorta obviates the purpose of having a tool.

Though, now that I've had a look at the glide branch is up in your repo, I think I have a better sense of what you're trying to do. This probably seems obvious, and like you've described it several times to me already, but let me write it out to make sure I'm correct: it looks like you're trying to define a root `$GOPATH` directory, with the intention that that `$GOPATH` be used exclusively for your project, and that you control the versions of the things in there.

This, generally, is not how `GOPATH` is intended to be used. Even the now mostly-defunct tools that did `GOPATH` manipulation didn't go this far, and it certainly doesn't work well for anything you're publishing publicly for others to use...as you seem to be discovering. `GOPATH` is intended to be a general dumping pool for code, *not* one in which you try to carefully control what's in it. If you try to swim upstream against that, you'll probably have a very bad time.

Assuming I understand your constraints correctly, this is what I'd do:

1. Stop trying to have your project live at `$GOPATH/src/hgapg`. You say in your README that it's not expected this project live at that path for terribly long, which is (I guess?) why you're trying to avoid that network path. But I don't see how that helps with the future name change - it just means, in the future they'll have to go from a working, simple network/local path relationship to another one, rather than going from a custom system to a simple network/local path. The change will still happen. No? So, to that end:
1. Let it live at `github.com/pb-cdunn/hgapg`, as its network identity would ordinarily dictate. 
1. Change the contents of `glide.yaml`'s `package` directive to `github.com/pb-cdunn/hgapg`.
2. Run your glide commands from within `$GOPATH/src/github.com/pb-cdunn/hgapg`. This will create and manipulate `$GOPATH/src/github.com/pb-cdunn/hgapg/glide.yaml`, and automatically populate `$GOPATH/src/github.com/pb-cdunn/hgapg/vendor` with the appropriate dependencies.
3. Commit your checked-out deps in `$GOPATH/src/github.com/pb-cdunn/hgapg/vendor`; this will not only make the package `go get`-able, if you care about that, but should meet with your ops folks' requirements that all source code can be checked out without go being installed.

**Comment by pb-cdunn** [comment]
Thank you very much for the thoughtful response.

**Comment by sdboyer** [comment]
np - hope you get this all sorted out.
