### ISSUE TITLE
Is Glide tool compatible with Windows?

### ISSUE THREAD

**Issue by JanSichula** [Masterminds/glide#51]
Hello,

Glide seems to be a great tool but I am a having a hard time to get it working on my Windows 8.1 Pro X64 development box. I can compile to exe file but when I then try to run "glide in" on a github.com/vgarvardt/rklotz clone repository, I end with a following error message.

" 
>> You are now gliding into a new shell. To exit, type 'exit'
Oops! exec: "": executable file not found in %PATH%
"

Is the project dependent on bash? Is it compatible with Windows?

Any advice will be greatly appreciated.

**Comment by mattfarina** [comment]
@JanSichula Prior to glide 0.5.0-beta1 I don't think glide will work on Windows. At least not out of the box. It was dependent on shells being there which is very Linux/Mac/*nix.

glide 0.5.0-beta1, which is designed to work with go 1.5 and the new vendor setup coming as part of Go itself, should work on Windows... sort of. I tested it today and it worked except for the command prompt colors which are still shell based. Instead of colors windows users see some funny characters. That needs to be fixed.

But, glide 0.5.0 isn't going to be backwards compatible with previous versions. That's because go 1.5 is making a change and we're embracing and supporting it.

I'm going to leave this open as I work out the remaining Windows issues.

**Comment by mattfarina** [comment]
Glide 0.5.0 is out with a Windows release. Please open a new issue if there are still Windows issues. I hope everything works well.

**Comment by JanSichula** [comment]
@mattfarina Thank you for your prompt response and all the effort. I would like to give a new version a try but on the other hand I do yet feel ready to move to a preproduction version of Go 1.5.

P. S. It looks like so many GoLang people are on the Linux or Mac boxes that they do not remember a minority of us on Windows. :-) But good to hear that in the case of Glide, it is being amended. :-)

**Comment by mattfarina** [comment]
@JanSichula I looked at what it would take to make glide 0.4 work on windows and it's a non-trivial amount of work. If it were easy I would make bugfix release. I'm happy to make things work on windows. When you're ready to go in on Go 1.5 I hope you'll consider using glide for your dependencies.
