### ISSUE TITLE
Is there a way to trim non dependency packages? 

### ISSUE THREAD

**Issue by VoR0220** [Masterminds/glide#515]
Currently, it seems glide does not do what it says it will do in that it grabs not just the package and its dependencies, but also the entire repo...this leads to a lot of vendor bloat. Is there, or could there be, an argument to only import the necessary packages and their subsequent dependencies into the vendor? Much appreciated.

**Comment by mattfarina** [comment]
This is a little bit of a complicated issue.

First, the quick fix. Have you looked at [glide-vc](https://github.com/sgotti/glide-vc)?

Right now Glide does not strip unused packages from a repo. We've not tackled that in part due to license concerns. A repo under a license and modification of that matters. We're being conservative while we learn more on the topic.

In the meantime there's a plugin you can use.

**Comment by VoR0220** [comment]
okay...well that makes much more sense now. Thanks a ton for the pointer.

**Comment by mattfarina** [comment]
We have a plugins section in the docs and this is a common enough question it's the first plugin listed.... http://glide.readthedocs.io/en/latest/plugins/
