### ISSUE TITLE
support semantic versioning of dependencies a la gopkg

### ISSUE THREAD

**Issue by azylman** [Masterminds/glide#52]
I'd love if the `glide.yml` file could specify semantic versions, so I could specify something like "version 1" and then it would pull the most recent `1.x.x` tag off of github, similar to what gopkg does

**Comment by mattfarina** [comment]
Yes! As a user of tools like npm and composer I know exactly what you mean. This seems like a good candidate for the 0.6.0 release.

**Comment by mattfarina** [comment]
I'm looking at two methods for version comparisons. One is strict to SemVer and the other is looser. I blogged about them recently at http://engineeredweb.com/blog/2015/go-version-compare/

**Comment by azylman** [comment]
fwiw, I've used [gopkg.in/blang/semver.v1](http://godoc.org/gopkg.in/blang/semver.v1) before and was happy with it (used it in [gitsem](https://github.com/clever/gitsem), which we use to version all of our libraries)

**Comment by technosophos** [comment]
I think that's a good idea. I would suggest that we support similar rules to gopkg.in, but with more precision:

v1 matches v1, v1.x, v1.x.y

v1.1 matches v1.1 and v1.1.y

v1.1.1 matches v1.1.1

And since one version of semver requires the v, while the other does not, we'd want to support the version without v, too.

**Comment by mattfarina** [comment]
For anyone wanting to follow along, the first step is to support branches and tags on [Masterminds/vcs](https://github.com/Masterminds/vcs). I started the branch feature/references to begin that work (and it's started). It will take me at least a few days to work through the best way to do this for each of the VCS.

**Comment by mattfarina** [comment]
Started the work on the feature/semver branch.

**Comment by azylman** [comment]
Can't wait to see this!

**Comment by mattfarina** [comment]
To keep the details up to speed for anyone wondering, there is an initial version on the _feature/semver_ branch. But, we're not all that keen on the constraints we can use and how this is working. I've been trying some existing semver libraries.

Due to the lack in features I've started a [semver](https://github.com/Masterminds/semver) library. The goal is to have many of the features you get in similar libraries in other languages. Once this is in good shape (in maybe a week) I'll update the _feature/semver_ branch and we'll look at merging.

This is the big thing I'm working on at the moment for Glide.

**Comment by mattfarina** [comment]
#114 (a pull request from a feature branch) added SemVer support. Still needs to be documented but it's there.

**Comment by mattfarina** [comment]
With the basic docs being present I'm going to close this. Happy SemVer'ing.

**Comment by azylman** [comment]
Awesome, thanks! Can't wait to try this out
