### ISSUE TITLE
Support `gb`'s manifest files for import

### ISSUE THREAD

**Issue by abourget** [Masterminds/glide#53]
`gb-vendor` uses a manifest.json which includes pretty much the same features as `glide`.

Same as with the term `vendor/`, I feel `manifest.json` is pretty tool agnostic, and could potentially be standardized.  Using `glide.yaml` is perhaps nicer (as its yaml), but more tool specific.. and crawling sub-dependencies in `vendor/` won't catch those other tools dependencies, uness `glide up` would also read those `manifest.json` and `Godeps/Godeps.json` files and *also* check out the repos, all at the same level under your local project's `vendor/` ? That'd be awesome.. 

There could also be some functionality to fix (in the local `glide.yaml` file) any conflicts between subpackages' own dependencies (when two require github.com/blah/blah), you need to decide which one you'll use, and pin it down. That'd be cool too!

Then, why not have a quick function to "git merge -s subtree" all of that in the local repo ?! w00t!

**Comment by mattfarina** [comment]
@abourget thanks for the thoughts.

Quick note, You might want to read up on `glide up --import` as it can read and import from Godeps and GPM. Might be a good idea to add gb-vendor support as well.

I would like to see a common format for describing packages and their dependencies. But, this is going to get hard and I would love input on how to simplify it. For example, package managers for other languages (e.g., [npm](http://npmjs.com) and [composer](https://getcomposer.org)) allow you to specify constraints around semantic versions in addition to checking out tags, branches, and commit id. This is something I'm hoping to support in an upcoming version (See #52 ).

How can we have a common format while supporting differing features?

If I read your comment correctly, you're suggesting the dependent project have their dependencies all pulled into your local projects `vendor/` folder. Why would you want that? The current setup in glide pulls the dependencies into each dependent projects `vendor/` folder. This keeps a similar separation and if I understand it correctly works similarly to npm in practice.

If two packages each have their own version of a dependency they should be fetching them from their own `vendor/` folder. That means if my package depends on packages A and B and both A and B depend on different versions of package C it's ok. Glide sticks dependent packages in the right `vendor/` folders and the compiler appears to handle this ok.

`glide pin` is a command that will look at your immediate dependencies and let you pin them down.

I'm not sure where you're going with the `git merge -s subtree` command. Is that for vendoring?

**Comment by technosophos** [comment]
This is an interesting idea.

`glide up` does optionally read other files like `Godeps/Godeps.json`. We could allow them to optionally be checked out at the top level, though right now we check them out into `vendor/` directories inside their respective projects (to avoid version conflicts). For sure, we should extend this to support `manifest.json`.

Because of things like SQL side-effect imports, we do still need to solve the problem where two dependencies clash. I was thinking of adding a directive that let you specify how to collapse dependencies. Something like:

```
required: [never, once, VERSION]
```

Where `never` makes sure we never ever get the dependency (a necessity in cases where people hand-vendor and then check things in), `once` gets a dependency only once (storing in the top level), preferring the newest version, and VERSION would be a specific version number.

Finally, we probably won't add git-specific merge logic, but I like the idea behind it. To this point, our approach has been to make it easy for users to add that last VCS-specific step.

**Comment by abourget** [comment]
ok, we can close this :)

**Comment by technosophos** [comment]
I think we should leave it open, with the desired outcome to be:

- glide can do `glide import gb` and import manifest files
- `glide get --import` and `glide up --import` will automatically parse and read manifest files

**Comment by mattfarina** [comment]
@abourget This week @technosophos added basic gb-vendor support with the commits 2821e2f11086236ed6179ff80e5685925cb97e7b, e4c80b23225fd9ec9c7aa3b80a83b3d6c8df12c7, and b390c8bf57f15096008d4d2903101bba7c2c3701.

Does this close this issue out?

**Comment by abourget** [comment]
Yes.. ok with me.

Le ven. 11 sept. 2015 10:03, Matt Farina <notifications@github.com> a
écrit :

**Comment by mattfarina** [comment]
Thanks.
