### ISSUE TITLE
Version wrong for 0.12.1

### ISSUE THREAD

**Issue by jrick** [Masterminds/glide#593]
Built the 0.12.1 release and see this:

```
PS C:\Users\jrick\go\src\github.com\Masterminds\glide> git checkout v0.12.1
Note: checking out 'v0.12.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8032c28... Removing build and dist for Plan 9 due to some issues.
PS C:\Users\jrick\go\src\github.com\Masterminds\glide> go install
PS C:\Users\jrick\go\src\github.com\Masterminds\glide> glide -v
glide version 0.12.0-dev
```

Not a huge deal but will make reporting issues a bit of a pain for those using the binary releases.

**Comment by mattfarina** [comment]
The binary releases use `-ldflags "-X main.version=${VERSION}"` where `VERSION` is from `$(shell git describe --tags)`. When `go install` is run this doesn't happen.

If you [go to a release and download a build](https://github.com/Masterminds/glide/releases/tag/v0.12.1) you'll find it properly reports the version. I just double checked.

It would be nice to have the internal version report the proper released version. #497 already exists for this issue and I know there is another issue I cannot find offhand where we discussed possible solutions. They were all too complicated in automation.

Closing only because it's a duplicate. Suggestions on fixing welcome.
