### ISSUE TITLE
go install "cannot find package" complaints

### ISSUE THREAD

**Issue by kchristidis** [Masterminds/glide#598]
After using Glide for my project's vendored packages, `go install` complains that it cannot find several packages in any of the resolution locations.

These seem to be packages that my direct dependencies depend on. For example, I get a complaint for`golang.org/x/oauth2`, which is used by `google.golang.org/grpc` (which is in turn properly vendored by Glide).

My package seems to build fine despite these complaints.

However, I've now lost [autocomplete functionality](https://atom.io/packages/autocomplete-go) since it depends on `go install`'s output.

Is there a way to fix this?

(For now, I just remove the `vendor` folder from my project, to eliminate the `go install` complaints.)

Thank you.

**Comment by mattfarina** [comment]
@kchristidis I think I can explain this.

Glide fetches and maintains the dependency tree in use. That is the things that are listed as `import` rather than all possible imports from all possible packages. That means if you import a repo but aren't using a sub-package in it the dependencies of that unused sub-package aren't fetched.

`go install` walks all the packages and subdirectories, including those in `vendor/` in an attempt to install everything. So, if one of those unused sub-packages from a dependency doesn't have all its dependencies it will fail to install something.

Lots of `go` tools look in `vendor/`. Because of this we created the command `glide nv`. You can use it like `go install $(glide nv)`. This will cause `go install` to walk all the directories except vendor.

This may not be ideal but highlights the issue.

Does this help?

**Comment by kchristidis** [comment]
Ah, I see what you're saying. It seems like Atom's autocomplete functionality will still be lost that way (because there's no way to have the plugin do a `go install $(glide nv)`, but I understand this is not an issue on your side.  Thank you for the explanation.

**Comment by 2upmedia** [comment]
Make sure that your Go source code is actually in the `$GOPATH` and that your environment is using the correct `$GOPATH` environment you have set. That was my mistake.
