### ISSUE TITLE
meaning of install

### ISSUE THREAD

**Issue by andrewarrow** [Masterminds/glide#610]
does install in glide world mean same as:

http://stackoverflow.com/questions/24601619/how-to-improve-golang-compilation-speed

like `go install -a github.com/mattn/go-sqlite3` will install binary of that and you never have to compile it again. Can I do same with all my glide deps?

**Comment by sdboyer** [comment]
no - "install" means "'install' my deps into `vendor` so that i can actually compile stuff.' the naming is derived from tools like, say, [npm](https://docs.npmjs.com/cli/install). though, yeah, in a compiled lang context, that can be a bit misleading.

actually compiling or placing binaries anywhere for use is strictly outside of glide's current scope.

**Comment by andrewarrow** [comment]
so if I have a large project with lots of deps, what's the glide way to install (real go meaning) them all? or you are saying there isn't? Could I go thru and go install -a each one? But that defeats the point og glide then right?

**Comment by sdboyer** [comment]
I think there's a basic misunderstanding here. Let's go back to this:

> like `go install -a github.com/mattn/go-sqlite3` will install binary of that

That's not what's happening there. That `go-sqlite3` package is not a main package, which means there is no binary TO install. What it does do is [re]compile the archive file, which lives at e.g., `$GOPATH/pkg/darwin_amd64/github.com/mattn/go-sqlite3.a` (if you're on a 64-bit OSX machine).

> and you never have to compile it again.

If the version/contents of the original source don't change, then you don't need to compile it again. If the source does change, though, then it has to be recompiled. Go's toolchain has no native concept of versioning (compare to, say, Rust/Cargo, where compiled objects are placed under a versioned directory hierarchy), so there's only ever one stored compiled object at a time. Addressing that particular issue is outside of glide's scope.

The important thing to understand here is that glide is _project-based_, whereas your questions seem to be more GOPATH-based.

For example "install them all": I assume you mean, basically, everything on your GOPATH. Or, in the case of `go install -a github.com/mattn/go-sqlite3`, everything transitively reachable from that package. The semantics there are, "find this path on my global $GOPATH, and recompile everything from there on down (and if it's a `package main`, place the compiled binary into $GOPATH/bin)". That assumes the idea of a GOPATH, that it's global, and that you can run the command from anywhere.

glide's commands are scoped to the project that it is operating _within_. Your cwd determines the scope; you have to be at or below the level of `$GOPATH/src/github.com/foo/bar` for it to work. There's no specifying of a package name on which to operate.

That's because glide (along with most of the other tools nowadays) aim to create a self-contained build environment that has all the correct _source code_ present in it, generally through the use of a `vendor` directory. The work being done here is all about picking of dependencies to use, recording those choices, and then making that a reality on disk in a way that all the existing tooling (go build, go test, go install) will transparently work with.

That's why glide is a dependency manager, not a build tool.

**Comment by andrewarrow** [comment]
thank you, that's great information. I'm starting to understand better. So, then if my go build take 30 seconds and i'm spending tons of time re-compiling not only stuff from vendor, but section of my own code that haven't changed, what's an eger developer to do? There must be some best practice so I can get that build take back down to like 3 seconds no?

**Comment by sdboyer** [comment]
> thank you, that's great information. I'm starting to understand better.

yay! 🎉 😄 

> So, then if my go build take 30 seconds and i'm spending tons of time re-compiling not only stuff from vendor, but section of my own code that haven't changed, what's an eger developer to do?

THAT's surprising (unless you're actually changing your vendor dir all the time) - those .a files should be cached, just like everything other transitive compile. Is the project you're working on public, so that I can try to replicate?

**Comment by mh-cbon** [comment]
> go install -a github.com/mattn/go-sqlite3

As mentionned by @sdboyer, this will install your go-sqlite3 `global` dependency to `$GOPATH/pkg/darwin_amd64/github.com/mattn/go-sqlite3.a`

__But__, if you have used glide to depends go-sqlite within your project (IE: it exists within your `./vendor` dir), then the first command shown here wont help you.

To fix this, use `go build -i` on your project, and your dependencies will be compiled and made available at a path like `$GOPATH/pkg/**/yourproject/vendor/**`.

That s what you want 'coz one of the rule of go imports is that the longest path wins, so when go imports sqlite3 for your project it will take the one within `vendor/` rather than the global one, then try to map it to a built asset, not find it, thus re compile it.

It s same as this SO [here](http://stackoverflow.com/a/39080359/4466350)

**Comment by andrewarrow** [comment]
ah, i get it now. closing. thanks all.
