### ISSUE TITLE
Glide always deletes vendor folder whenever getting a new package

### ISSUE THREAD

**Issue by hirikarate** [Masterminds/glide#643]
_Glide version_: v0.12.3
_Env_: Dell laptop with Windows 7 Proffesional x64
_Issue_:
I'm using LiteIDE to work with Golang, whenever I issue command `glide get github.com/....` to fetch a dependency package, Glide throws error `[ERROR] Unable to export dependencies to vendor directory: GetFileAttributesEx:{my project root}\src\vendor\github.com\beego\bee: Access is denied.`
I have to CLOSE LiteIDE completely so that I can run that command again, and I see Glide remove the whole `vendor` folder (including all its subfolders), then creates a new one with the existing packages, plus the new package.

Is this an expected behavior of Glide?
If no, how do I fix it?
If yes, then why?

Here is my screenshot from windows command console:
![image](https://cloud.githubusercontent.com/assets/5905553/19513243/74ba47ba-9619-11e6-8ec9-09a9c2d47a35.png)

**Comment by franciscocpg** [comment]
@hirikarate, about removing the vendor directory it is an expected behavior and here is the explanation: https://github.com/Masterminds/glide/issues/585. 
About having to close LiteIDE because of `access denied` that's the way Windows works with its file lock mechanism. Maybe you could submit an issue at LiteIDE project but I am not sure if could help. Anyway, this is not a glide error.
