### ISSUE TITLE
Option to disable cache

### ISSUE THREAD

**Issue by gm42** [Masterminds/glide#656]
It is taking me 1 hour to generate the glide.lock file, even if all the dependencies in vendor/ are at the correct version, just because glide is busy cloning repositories in `~/.glide` without anybody telling to do so explicitly - and there is not even an option to disable it.

I am sorry but these "smart caches" are everything but vital and always useful. There are scenarios where one just wants to assert that the dependencies are at the versions in `glide.lock`, not have glide refresh its cache (think about throw-away EC2 instances etc).

I think there should be the possibility to disable the cache, and for sure it should not be enabled by default in any case.

**Comment by mattfarina** [comment]
If Glide disables the cache where does it Glide get the source for a version or revision to inject into the `vendor/` directory or scan (in the case of `update`) for transitive dependencies?

**Comment by SydOps** [comment]
I have issue when run in Jenkins job with glide, jenkins need dependecy between each job, hard code cache to ~/.glide/cache is not good design.

**Comment by SydOps** [comment]
@mattfarina 

I have issue when run in Jenkins job with glide, jenkins need isolation between each job, hard code cache to ~/.glide/cache as share folder is not good design. 

Can we have something like virtualenv in python?

    virtualenv ENV

So all cached, packages are saved under currently `ENV` folder

**Comment by sdboyer** [comment]
@SydOps we really can't. As we were just discussing over at #692, "cache" is not exactly the best word, but it's close enough that we use it. It'd be more accurate to call it "scratch space," or something.

Yeah, this is a use case we're very cognizant of. It is, in general, hard to coordinate activity between processes (of course). We may have a solution where multiple glide processes can share access to a single cache at the same time, but that's not on the short or medium horizon.

Fortunately, it's not hardcoded to `.glide/cache`. You can pass the `--home` parameter, which otherwise defaults to `~/.glide`. Generate a random dirname in your jenkins job, and you should be fine (albeit with potentially a lot of wasteful network activity).

**Comment by SydOps** [comment]
@sdboyer 

Thanks, I will use `--home` from now on.

**Comment by SydOps** [comment]
@sdboyer 

Before you close the ticket, could we have a system environment varaible to set the glide cache path?

**Comment by sdboyer** [comment]
it exists - `$GLIDE_HOME`
